apiVersion: gardener.clusters.openmcp.cloud/v1alpha1
kind: ProviderConfig
metadata:
  name: shoot-small
spec:
  landscapeRef:
    name: gardener-landscape
  project: pm-cc-d2
  providerRef:
    name: gardener
  shootTemplate:
    spec:
      cloudProfile:
        kind: CloudProfile
        name: converged-cloud-ora-fp
      kubernetes:
        version: "1.33.9" # e.g. "1.32"
      maintenance:
        autoUpdate:
          kubernetesVersion: true
        timeWindow:
          begin: 220000+0200
          end: 230000+0200
      networking:
        nodes: 10.250.0.0/16
        type: calico
      provider:
        controlPlaneConfig:
          apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
          kind: ControlPlaneConfig
          zone: eu-de-1b # e.g. europe-west1-c
          loadBalancerProvider: f5
        infrastructureConfig:
          apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
          kind: InfrastructureConfig
          networks:
            workers: 10.250.1.0/24
          floatingPoolName: FloatingIP-external-ora-01
        type: openstack
        workers:
        - cri:
            name: containerd
          machine:
            architecture: amd64
            image:
              name: gardenlinux
              version: "1877.13.0" # e.g. "1592.9.0"
            type: g_c2_m4
          maxSurge: 1
          maximum: 5
          minimum: 1
          name: default-worker
          volume:
            size: 50Gi
            #type: default
          zones:
          - eu-de-1b # e.g. europe-west1-c
      purpose: evaluation
      region: eu-de-1 # e.g. europe-west1
      secretBindingName: cc-eu-de-1
